import { StyleSheet } from 'react-native'

export const appStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F7F8F5',
    paddingHorizontal: 28,
    paddingTop: 48,
  },
  eyebrow: {
    color: '#277C65',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    marginBottom: 12,
  },
  title: {
    color: '#172329',
    fontSize: 30,
    fontWeight: '700',
    letterSpacing: 0,
  },
  body: {
    color: '#526168',
    fontSize: 16,
    lineHeight: 23,
    marginTop: 10,
  },
  action: {
    color: '#277C65',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 32,
  },
  tabBarLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  addFoodScreen: {
    flex: 1,
    backgroundColor: '#F7F8F5',
    paddingHorizontal: 20,
    paddingTop: 48,
  },
  addFoodSearchInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D9E1E5',
    borderRadius: 12,
    borderWidth: 1,
    color: '#172329',
    fontSize: 16,
    marginTop: 20,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  addFoodStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  addFoodStatusText: {
    color: '#526168',
    fontSize: 14,
  },
  addFoodErrorText: {
    color: '#B53434',
    fontSize: 14,
    marginTop: 18,
  },
  addFoodEmptyText: {
    color: '#526168',
    fontSize: 14,
    marginTop: 18,
  },
  addFoodListContent: {
    paddingBottom: 40,
    paddingTop: 20,
  },
  addFoodResultCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5EBEE',
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 12,
    padding: 16,
  },
  addFoodFoodName: {
    color: '#172329',
    fontSize: 16,
    fontWeight: '700',
  },
  addFoodFoodMeta: {
    color: '#526168',
    fontSize: 13,
    marginTop: 4,
  },
  addFoodResultMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  addFoodCalorieText: {
    color: '#277C65',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 12,
  },
  addFoodNutrientText: {
    color: '#526168',
    fontSize: 13,
    marginTop: 6,
  },
  addFoodServingOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  addFoodServingOption: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D9E1E5',
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  addFoodServingOptionSelected: {
    backgroundColor: '#E7F3EE',
    borderColor: '#277C65',
  },
  addFoodServingOptionText: {
    color: '#526168',
    fontSize: 13,
  },
  addFoodServingOptionTextSelected: {
    color: '#205F4F',
    fontWeight: '700',
  },
  addFoodQuantityRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  addFoodQuantityInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D9E1E5',
    borderRadius: 6,
    borderWidth: 1,
    color: '#172329',
    fontSize: 15,
    minWidth: 72,
    paddingHorizontal: 10,
    paddingVertical: 7,
    textAlign: 'center',
  },
  addFoodSuccessText: {
    color: '#277C65',
    fontSize: 14,
    marginTop: 18,
  },
  addFoodAddButton: {
    alignItems: 'center',
    backgroundColor: '#277C65',
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  addFoodAddButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  addFoodAddButtonDisabled: {
    opacity: 0.55,
  },
  addFoodAddButtonPressed: {
    opacity: 0.8,
  },
  dailyLogScreen: {
    flex: 1,
    backgroundColor: '#F7F8F5',
    paddingHorizontal: 16,
    paddingTop: 28,
  },
  dailyLogTitle: {
    color: '#172329',
    fontSize: 26,
    fontWeight: '700',
  },
  dailyLogDateNavigation: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  dailyLogDateButton: {
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  dailyLogDateButtonText: {
    color: '#277C65',
    fontSize: 13,
    fontWeight: '700',
  },
  dailyLogDateButtonDisabled: {
    opacity: 0.4,
  },
  dailyLogDateText: {
    color: '#172329',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  dailyLogListContent: {
    flexGrow: 1,
    paddingBottom: 16,
    paddingTop: 12,
  },
  dailyLogFoodRow: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5EBEE',
    borderRadius: 6,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  dailyLogFoodTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dailyLogFoodDetails: {
    flex: 1,
    paddingRight: 8,
  },
  dailyLogFoodCalories: {
    color: '#277C65',
    fontSize: 14,
    fontWeight: '700',
  },
  dailyLogFoodTime: {
    color: '#6E7B82',
    fontSize: 12,
    marginTop: 4,
  },
  dailyLogFoodNutrition: {
    color: '#526168',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  dailyLogFoodActions: {
    alignItems: 'flex-end',
    marginTop: 6,
  },
  dailyLogDeleteButton: {
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 8,
  },
  dailyLogDeleteButtonText: {
    color: '#B53434',
    fontSize: 13,
    fontWeight: '700',
  },
  dailyLogSummary: {
    backgroundColor: '#F7F8F5',
    borderTopColor: '#D9E1E5',
    borderTopWidth: 1,
    paddingBottom: 8,
    paddingTop: 12,
  },
  dailyLogSummaryTitle: {
    color: '#172329',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 10,
  },
  dailyLogSummaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dailyLogSummaryItem: {
    flex: 1,
    minWidth: 0,
  },
  dailyLogSummaryValue: {
    color: '#172329',
    fontSize: 13,
    fontWeight: '700',
  },
  dailyLogSummaryLabel: {
    color: '#6E7B82',
    fontSize: 11,
    marginTop: 3,
  },
})